#!/bin/bash -e

# inspired by openstreetmap-carto's shield
# generation scripts at
# https://github.com/gravitystorm/openstreetmap-carto/tree/master/scripts

# all generated symbols are 10x10 units

outdir="symbolsTM" # trail marker symbols

# name;fill;border
colors=\
'black;#000;#000
red;#e33;#000
orange;#fa0;#000
yellow;#ff0;#000
green;#3a2;#000
blue;#28f;#000
cyan;#2dd;#000
white;#fff;#000
brown;#950;#000'

function output() {
   name=$1
   svgBody=$2
   filename="$outdir/$name.svg"
   echo "Generating $filename"
   
   rm -f $filename
   touch $filename
   echo "<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' viewBox='0 0 10 10'>" >>$filename
   echo "$svgBody" >>$filename
   echo "</svg>" >>$filename
}


mkdir -pv $outdir

for c in $colors; do
  colorname=${c%%;*}
  fill=${c#*;};fill=${fill%;*}
  border=${c##*;}
  
  # circle
  svg="<circle cx='5' cy='5' r='5' fill='$border'/>
       <circle cx='5' cy='5' r='4.5' fill='$fill'/>"
  output "circle_$colorname" "$svg"
  
  # square
  svg="<rect x='0.5' y='0.5' width='9' height='9' fill='$border'/>
       <rect x='1' y='1' width='8' height='8' fill='$fill'/>"
  output "square_$colorname" "$svg"
  
  # rectangle (horizontal)
  svg="<rect x='0' y='2' width='10' height='6' fill='$border' />
       <rect x='0.5' y='2.5' width='9' height='5' fill='$fill' />"
  output "rectangle_$colorname" "$svg"
  
  # diamond
  svg="<polygon points='5,0 10,5 5,10 0,5' fill='$border' />
       <polygon points='5,0.5 9.5,5 5,9.5 0.5,5' fill='$fill' />"
  output "diamond_$colorname" "$svg"
  
  # triangle (pointing up)
  svg="<polygon points='5,0 10,10 0,10' fill='$border' />
       <polygon points='5,0.5 9.5,9.5 0.5,9.5' fill='$fill' />"
  output "triangle_$colorname" "$svg"
  
done


